# -*- coding: utf-8 -*-
"""UNIT 2 NOICE REDUCTION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWWpaDUQT5YJyRcuOFX5YuMEeZPczcLt

TYPES OF NOICE

1. Gaussian Noise
2. Impulse (Salt-and-Pepper) Noise
3. Speckle Noise
4. Poisson Noise

**STEP 1: READ AN IMAGE AND DISPLAY THE ORIGINAL IMAGE**
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
from google.colab import files
img=cv2.imread("/content/cameraman.JPG")
cv2_imshow(img)

"""**STEP 2: ADD GAUSSIAN NOICE**"""

# Normalize image to [0,1]
img_norm = img / 255.0

# Create Gaussian noise
mean = 0
var = 0.01
sigma = var ** 0.5
gauss = np.random.normal(mean, sigma, img_norm.shape)

# Add noise and clip to [0,1]
noisy_img = img_norm + gauss
noisy_img = np.clip(noisy_img, 0, 1)

# Convert back to uint8
noisy_img = (noisy_img * 255).astype(np.uint8)

# Display the noisy image
plt.imshow(cv2.cvtColor(noisy_img, cv2.COLOR_BGR2RGB))
plt.title("Gaussian Noise Image")
plt.axis('off')
plt.show()

# Denoise Gaussian Noise
denoised_gaussian = cv2.GaussianBlur(gaussian_noise_img, (5,5), 1.5)

# Display
plt.imshow(cv2.cvtColor(denoised_gaussian, cv2.COLOR_BGR2RGB))
plt.title("Gaussian Noise Denoised")
plt.axis('off')
plt.show()

"""**STEP 3 : ADD SALT AND PEPPER NOICE**"""

def salt_and_pepper_noise(image, amount=0.05):
    noisy = image.copy()
    num_salt = np.ceil(amount * image.size * 0.5).astype(int)
    num_pepper = np.ceil(amount * image.size * 0.5).astype(int)

    # Salt noise (white pixels)
    coords = [np.random.randint(0, i - 1, num_salt) for i in image.shape[:2]]
    noisy[coords[0], coords[1]] = 255

    # Pepper noise (black pixels)
    coords = [np.random.randint(0, i - 1, num_pepper) for i in image.shape[:2]]
    noisy[coords[0], coords[1]] = 0

    return noisy

noisy_img = salt_and_pepper_noise(img, amount=0.05)

plt.imshow(cv2.cvtColor(noisy_img, cv2.COLOR_BGR2RGB))
plt.title("Salt and Pepper Noise")
plt.axis('off')
plt.show()

# First add salt-and-pepper noise to your image
sp_noise_img = salt_and_pepper_noise(img, amount=0.05)

# Then denoise using median filter on the noisy image
denoised_sp = cv2.medianBlur(sp_noise_img, 5)

# Display denoised image
plt.imshow(cv2.cvtColor(denoised_sp, cv2.COLOR_BGR2RGB))
plt.title("Salt-and-Pepper Noise Denoised")
plt.axis('off')
plt.show()

"""**STEP 4: ADD SPECKLE NOICE**"""

import numpy as np
import cv2
import matplotlib.pyplot as plt

def add_speckle_noise(img):
    noise = np.random.randn(*img.shape[:2])[:, :, None]
    noisy = img/255 + (img/255)*noise
    noisy = np.clip(noisy, 0, 1)
    return (noisy * 255).astype(np.uint8)

speckle_img = add_speckle_noise(img)
denoised = cv2.medianBlur(speckle_img, 5)


plt.subplot(1,2,1)
plt.imshow(cv2.cvtColor(speckle_img, cv2.COLOR_BGR2RGB))
plt.title('Speckle Noise')
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(cv2.cvtColor(denoised, cv2.COLOR_BGR2RGB))
plt.title('Denoised')
plt.axis('off')

plt.show()

"""**STEP 4: ADD POISSON NOICE**"""

def add_poisson_noise(image):
    # Normalize image to [0,1]
    img_norm = image / 255.0

    # Calculate unique values to scale noise properly
    vals = len(np.unique(img_norm))
    vals = 2 ** np.ceil(np.log2(vals))  # next power of 2

    # Apply Poisson noise
    noisy = np.random.poisson(img_norm * vals) / float(vals)

    # Clip to valid range and convert back
    noisy = np.clip(noisy, 0, 1)
    noisy = (noisy * 255).astype(np.uint8)

    return noisy

poisson_img = add_poisson_noise(img)

plt.imshow(cv2.cvtColor(poisson_img, cv2.COLOR_BGR2RGB))
plt.title("Poisson Noise Image")
plt.axis('off')
plt.show()

# Denoise Poisson noise
denoised_poisson = cv2.fastNlMeansDenoisingColored(poisson_img, None, 10, 10, 7, 21)

# Display denoised image
plt.imshow(cv2.cvtColor(denoised_poisson, cv2.COLOR_BGR2RGB))
plt.title("Poisson Noise Denoised")
plt.axis('off')
plt.show()

