# -*- coding: utf-8 -*-
"""WORKOUTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fjv0vDg6S3iCCgtOw8Dynj-0z-fwGSY3
"""



import numpy as np
import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
img=cv2.imread("/content/rose.jpeg")
print(img)

cv2_imshow(img)

height, width, channels = img.shape
print("Width:", width)
print("Height:", height)
print("Channels:", channels)

import numpy as np
import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
print("original image")
img=cv2.imread("/content/rose.jpeg")
cv2_imshow(img)
print("grayscale image")
img1=cv2.imread("/content/rose.jpeg",0)
cv2_imshow(img1)
# Apply binary threshold (128)
binary_img = (img1 > 128).astype(np.uint8) * 255

# Display binary image
plt.imshow(binary_img, cmap='gray')
plt.title('Binary Image')
plt.axis('off')
plt.show()

import pandas as pd

from numpy import asarray
data=asarray(img)
print(data)

import imutils
r1=imutils.rotate(img,45)
cv2_imshow(r1)

# Select a pixel location
x, y = 50, 100  # Row (y), Column (x) coordinates

# Get the pixel value
pixel_value = img[y, x]
print(f"\nPixel at (x={x}, y={y}) -> BGR values:", pixel_value)

# Get individual B, G, R values
blue, green, red = pixel_value
print("Blue:", blue)
print("Green:", green)
print("Red:", red)

# Number of channels:
channels = img.shape[2]
print("Number of channels:", channels)