# -*- coding: utf-8 -*-
"""UNIT 2 CONTRAST ENHANCEMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvxltozYov0lS85Fvw_V_s8eHuhvphEN

CONTRAST ENHANCEMENT

**STEP 1: READ AN IMAGE AND DISPLAY BOTH COLOR IMAGE AND GRAY SCALE IMAGE**
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
from google.colab import files
print("original image")
img=cv2.imread("/content/rose.jpeg")
cv2_imshow(img)
print("Gray scale image")
img1=cv2.imread("/content/rose.jpeg",0)
cv2_imshow(img1)

"""Plot histogram of color images to see pixel intensity distribution.

"""

# Split channels (B, G, R)
b, g, r = cv2.split(img)

plt.hist(r.ravel(), bins=256, color='r', alpha=0.5)
plt.hist(g.ravel(), bins=256, color='g', alpha=0.5)
plt.hist(b.ravel(), bins=256, color='b', alpha=0.5)

plt.show()

"""Plot histogram of grayscale to see pixel intensity distribution.

"""

# Calculate histogram for grayscale image
hist = cv2.calcHist([img1], [0], None, [256], [0, 256])

# Plot histogram
plt.plot(hist, color='black')
plt.title('Grayscale Histogram')
plt.xlabel('Pixel Intensity')
plt.ylabel('Number of Pixels')
plt.xlim([0, 256])
plt.show()

"""Apply Histogram Equalization on Grayscale Image

"""

img_eq = cv2.equalizeHist(img1)

plt.subplot(1,2,1)
plt.imshow(img1, cmap='gray')
plt.title('Original Grayscale Image')
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(img_eq, cmap='gray')
plt.title('Equalized Image')
plt.axis('off')

plt.show()